### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by quillaja** [quillaja/goasm#1]
- [ ] add more mnemonics to the colorizer's regexs
- [ ] move the xml version of the colorizer rules to json
- [x] add snippets for special characters ("middle dot character U+00B7 and the division slash U+2215 in identifiers"
